/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Report that the service is up, along with its version.
     */
    get: operations["health_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rules/meta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Meta */
    get: operations["get_meta_api_v1_rules_meta_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rules/races": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Races */
    get: operations["get_races_api_v1_rules_races_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rules/classes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Classes */
    get: operations["get_classes_api_v1_rules_classes_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rules/classes/{slug}/progression/{level}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Class Progression */
    get: operations["get_class_progression_api_v1_rules_classes__slug__progression__level__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rules/skills": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Skills */
    get: operations["get_skills_api_v1_rules_skills_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rules/feats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Feats */
    get: operations["get_feats_api_v1_rules_feats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rules/weapons": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Weapons */
    get: operations["get_weapons_api_v1_rules_weapons_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rules/armor": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Armor */
    get: operations["get_armor_api_v1_rules_armor_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rules/conditions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Conditions */
    get: operations["get_conditions_api_v1_rules_conditions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rules/spells": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Spells */
    get: operations["get_spells_api_v1_rules_spells_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/characters": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Characters */
    get: operations["list_characters_api_v1_characters_get"];
    put?: never;
    /** Create Character */
    post: operations["create_character_api_v1_characters_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/characters/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import Character */
    post: operations["import_character_api_v1_characters_import_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/characters/{character_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Character */
    get: operations["get_character_api_v1_characters__character_id__get"];
    /** Replace Character */
    put: operations["replace_character_api_v1_characters__character_id__put"];
    post?: never;
    /** Delete Character */
    delete: operations["delete_character_api_v1_characters__character_id__delete"];
    options?: never;
    head?: never;
    /** Patch Character */
    patch: operations["patch_character_api_v1_characters__character_id__patch"];
    trace?: never;
  };
  "/api/v1/characters/{character_id}/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export Character */
    get: operations["export_character_api_v1_characters__character_id__export_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/characters/{character_id}/duplicate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Duplicate Character */
    post: operations["duplicate_character_api_v1_characters__character_id__duplicate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/characters/{character_id}/combat-sheet": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Combat Sheet */
    get: operations["combat_sheet_api_v1_characters__character_id__combat_sheet_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/derive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Derive */
    post: operations["derive_api_v1_derive_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ACDTO */
    ACDTO: {
      /** Total */
      total: number;
      /** Touch */
      touch: number;
      /** Flat Footed */
      flat_footed: number;
      /** Max Dex Cap */
      max_dex_cap: number | null;
      /** Breakdown */
      breakdown: components["schemas"]["BreakdownEntry"][];
      /** Suppressed */
      suppressed: components["schemas"]["SuppressedEntry"][];
    };
    /** AbilityDTO */
    AbilityDTO: {
      /** Name */
      name: string;
      /** Abbr */
      abbr: string;
      /** Uses */
      uses: string;
    };
    /** AbilityScoreDTO */
    AbilityScoreDTO: {
      /** Score */
      score: number;
      /** Modifier */
      modifier: number;
      /** Base */
      base: number;
      /** Racial */
      racial: number;
      /** Level Increment */
      level_increment: number;
      /** Damage */
      damage: number;
    };
    /** ActionTypeDTO */
    ActionTypeDTO: {
      /** Type */
      type: string;
      /** Notes */
      notes?: string | null;
    };
    /** ActiveEffectIn */
    ActiveEffectIn: {
      /** Id */
      id?: string;
      /** Name */
      name: string;
      /** Modifiers */
      modifiers?: components["schemas"]["ModifierIn"][];
      /** Remaining Rounds */
      remaining_rounds?: number | null;
    };
    /** ArmorDTO */
    ArmorDTO: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Category */
      category: string;
      /** Price Gp */
      price_gp: number;
      /** Armor Bonus */
      armor_bonus: number;
      /** Max Dex */
      max_dex?: number | null;
      /** Armor Check Penalty */
      armor_check_penalty: number;
      /** Arcane Spell Failure Pct */
      arcane_spell_failure_pct: number;
      /** Speed 30 */
      speed_30?: string | null;
      /** Speed 20 */
      speed_20?: string | null;
      /** Weight */
      weight?: string | null;
    };
    /** AttackDTO */
    AttackDTO: {
      /** Weapon */
      weapon: string;
      /** Is Ranged */
      is_ranged: boolean;
      /** Attack Line */
      attack_line: string;
      attack: components["schemas"]["ValueBreakdown"];
      /** Damage Expression */
      damage_expression: string | null;
      damage: components["schemas"]["ValueBreakdown"];
      /** Threat Range */
      threat_range: number;
      /** Crit Multiplier */
      crit_multiplier: number;
      /** Damage Type */
      damage_type: string | null;
      /** Range Increment */
      range_increment: string | null;
      /** Is Proficient */
      is_proficient: boolean;
    };
    /** BabDTO */
    BabDTO: {
      /** Total */
      total: number;
      /** Iteratives */
      iteratives: number[];
    };
    /**
     * BonusTypesDTO
     * @description The stacking classification, verbatim from ``sistema.tipos_de_bonificador``.
     */
    BonusTypesDTO: {
      /** Always Stack */
      always_stack: string[];
      /** Do Not Stack */
      do_not_stack: string[];
      /** Penalties */
      penalties: string;
      /** Note */
      note?: string | null;
    };
    /** BreakdownEntry */
    BreakdownEntry: {
      /** Label */
      label: string;
      /** Value */
      value: number;
      /** Type */
      type: string | null;
      /** Source */
      source: string;
    };
    /**
     * CharacterCreate
     * @description Body for ``POST /characters``.
     */
    CharacterCreate: {
      /**
       * Kind
       * @default pc
       * @enum {string}
       */
      kind: "pc" | "npc";
      /**
       * Name
       * @default Nuevo personaje
       */
      name: string;
      /** Player Name */
      player_name?: string | null;
      /**
       * Race
       * @default humano
       */
      race: string;
      /** Alignment */
      alignment?: string | null;
      /** Size */
      size?: string | null;
      /** Speed Ft */
      speed_ft?: number | null;
      /** Notes */
      notes?: string | null;
      /** Portrait Url */
      portrait_url?: string | null;
      /** Class Levels */
      class_levels?: components["schemas"]["ClassLevelIn"][];
      /** Base Scores */
      base_scores?: {
        [key: string]: number;
      };
      /** Racial Bonus Choices */
      racial_bonus_choices?: {
        [key: string]: number;
      };
      /** Ability Damage */
      ability_damage?: {
        [key: string]: number;
      };
      /** Level Ability Increments */
      level_ability_increments?: {
        [key: string]: number;
      };
      /**
       * Max Hp
       * @default 0
       */
      max_hp: number;
      /**
       * Current Hp
       * @default 0
       */
      current_hp: number;
      /**
       * Temporary Hp
       * @default 0
       */
      temporary_hp: number;
      /**
       * Nonlethal Damage
       * @default 0
       */
      nonlethal_damage: number;
      /**
       * Hp Roll Mode
       * @default manual
       * @enum {string}
       */
      hp_roll_mode: "manual" | "average" | "max_first_then_average";
      /** Skill Ranks */
      skill_ranks?: {
        [key: string]: number;
      };
      /** Skill Misc Modifiers */
      skill_misc_modifiers?: {
        [key: string]: number;
      };
      /** Feats */
      feats?: string[];
      /** Feat Options */
      feat_options?: {
        [key: string]: string;
      };
      armor?: components["schemas"]["EquippedArmorIn"] | null;
      shield?: components["schemas"]["EquippedArmorIn"] | null;
      /** Weapons */
      weapons?: components["schemas"]["EquippedWeaponIn"][];
      /**
       * Natural Armor Bonus
       * @default 0
       */
      natural_armor_bonus: number;
      /**
       * Deflection Bonus
       * @default 0
       */
      deflection_bonus: number;
      /**
       * Other Ac Modifiers
       * @default 0
       */
      other_ac_modifiers: number;
      /** Load Carried Lb */
      load_carried_lb?: number | null;
      /** Active Conditions */
      active_conditions?: string[];
      /** Active Effects */
      active_effects?: components["schemas"]["ActiveEffectIn"][];
      /** Modifiers */
      modifiers?: components["schemas"]["ModifierIn"][];
      stances?: components["schemas"]["StancesIn"];
      /**
       * Initiative Misc
       * @default 0
       */
      initiative_misc: number;
      /**
       * Is Flat Footed
       * @default false
       */
      is_flat_footed: boolean;
      /**
       * Dexterity Denied
       * @default false
       */
      dexterity_denied: boolean;
    };
    /**
     * CharacterImport
     * @description Body for ``POST /characters/import``: an exported document, whose
     *     server-managed fields (id, timestamps) are ignored so a raw export re-imports.
     */
    CharacterImport: {
      /**
       * Kind
       * @default pc
       * @enum {string}
       */
      kind: "pc" | "npc";
      /**
       * Name
       * @default Nuevo personaje
       */
      name: string;
      /** Player Name */
      player_name?: string | null;
      /**
       * Race
       * @default humano
       */
      race: string;
      /** Alignment */
      alignment?: string | null;
      /** Size */
      size?: string | null;
      /** Speed Ft */
      speed_ft?: number | null;
      /** Notes */
      notes?: string | null;
      /** Portrait Url */
      portrait_url?: string | null;
      /** Class Levels */
      class_levels?: components["schemas"]["ClassLevelIn"][];
      /** Base Scores */
      base_scores?: {
        [key: string]: number;
      };
      /** Racial Bonus Choices */
      racial_bonus_choices?: {
        [key: string]: number;
      };
      /** Ability Damage */
      ability_damage?: {
        [key: string]: number;
      };
      /** Level Ability Increments */
      level_ability_increments?: {
        [key: string]: number;
      };
      /**
       * Max Hp
       * @default 0
       */
      max_hp: number;
      /**
       * Current Hp
       * @default 0
       */
      current_hp: number;
      /**
       * Temporary Hp
       * @default 0
       */
      temporary_hp: number;
      /**
       * Nonlethal Damage
       * @default 0
       */
      nonlethal_damage: number;
      /**
       * Hp Roll Mode
       * @default manual
       * @enum {string}
       */
      hp_roll_mode: "manual" | "average" | "max_first_then_average";
      /** Skill Ranks */
      skill_ranks?: {
        [key: string]: number;
      };
      /** Skill Misc Modifiers */
      skill_misc_modifiers?: {
        [key: string]: number;
      };
      /** Feats */
      feats?: string[];
      /** Feat Options */
      feat_options?: {
        [key: string]: string;
      };
      armor?: components["schemas"]["EquippedArmorIn"] | null;
      shield?: components["schemas"]["EquippedArmorIn"] | null;
      /** Weapons */
      weapons?: components["schemas"]["EquippedWeaponIn"][];
      /**
       * Natural Armor Bonus
       * @default 0
       */
      natural_armor_bonus: number;
      /**
       * Deflection Bonus
       * @default 0
       */
      deflection_bonus: number;
      /**
       * Other Ac Modifiers
       * @default 0
       */
      other_ac_modifiers: number;
      /** Load Carried Lb */
      load_carried_lb?: number | null;
      /** Active Conditions */
      active_conditions?: string[];
      /** Active Effects */
      active_effects?: components["schemas"]["ActiveEffectIn"][];
      /** Modifiers */
      modifiers?: components["schemas"]["ModifierIn"][];
      stances?: components["schemas"]["StancesIn"];
      /**
       * Initiative Misc
       * @default 0
       */
      initiative_misc: number;
      /**
       * Is Flat Footed
       * @default false
       */
      is_flat_footed: boolean;
      /**
       * Dexterity Denied
       * @default false
       */
      dexterity_denied: boolean;
    };
    /** CharacterListResponse */
    CharacterListResponse: {
      /** Items */
      items: components["schemas"]["CharacterSummary"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /**
     * CharacterPatch
     * @description Partial update: only provided fields change (``exclude_unset`` semantics).
     */
    CharacterPatch: {
      /** Kind */
      kind?: ("pc" | "npc") | null;
      /** Name */
      name?: string | null;
      /** Player Name */
      player_name?: string | null;
      /** Race */
      race?: string | null;
      /** Alignment */
      alignment?: string | null;
      /** Size */
      size?: string | null;
      /** Speed Ft */
      speed_ft?: number | null;
      /** Notes */
      notes?: string | null;
      /** Portrait Url */
      portrait_url?: string | null;
      /** Class Levels */
      class_levels?: components["schemas"]["ClassLevelIn"][] | null;
      /** Base Scores */
      base_scores?: {
        [key: string]: number;
      } | null;
      /** Racial Bonus Choices */
      racial_bonus_choices?: {
        [key: string]: number;
      } | null;
      /** Ability Damage */
      ability_damage?: {
        [key: string]: number;
      } | null;
      /** Level Ability Increments */
      level_ability_increments?: {
        [key: string]: number;
      } | null;
      /** Max Hp */
      max_hp?: number | null;
      /** Current Hp */
      current_hp?: number | null;
      /** Temporary Hp */
      temporary_hp?: number | null;
      /** Nonlethal Damage */
      nonlethal_damage?: number | null;
      /** Hp Roll Mode */
      hp_roll_mode?: ("manual" | "average" | "max_first_then_average") | null;
      /** Skill Ranks */
      skill_ranks?: {
        [key: string]: number;
      } | null;
      /** Skill Misc Modifiers */
      skill_misc_modifiers?: {
        [key: string]: number;
      } | null;
      /** Feats */
      feats?: string[] | null;
      /** Feat Options */
      feat_options?: {
        [key: string]: string;
      } | null;
      armor?: components["schemas"]["EquippedArmorIn"] | null;
      shield?: components["schemas"]["EquippedArmorIn"] | null;
      /** Weapons */
      weapons?: components["schemas"]["EquippedWeaponIn"][] | null;
      /** Natural Armor Bonus */
      natural_armor_bonus?: number | null;
      /** Deflection Bonus */
      deflection_bonus?: number | null;
      /** Other Ac Modifiers */
      other_ac_modifiers?: number | null;
      /** Load Carried Lb */
      load_carried_lb?: number | null;
      /** Active Conditions */
      active_conditions?: string[] | null;
      /** Active Effects */
      active_effects?: components["schemas"]["ActiveEffectIn"][] | null;
      /** Modifiers */
      modifiers?: components["schemas"]["ModifierIn"][] | null;
      stances?: components["schemas"]["StancesIn"] | null;
      /** Initiative Misc */
      initiative_misc?: number | null;
      /** Is Flat Footed */
      is_flat_footed?: boolean | null;
      /** Dexterity Denied */
      dexterity_denied?: boolean | null;
    };
    /**
     * CharacterRead
     * @description A stored character, with server-managed identity and timestamps.
     */
    CharacterRead: {
      /**
       * Kind
       * @default pc
       * @enum {string}
       */
      kind: "pc" | "npc";
      /**
       * Name
       * @default Nuevo personaje
       */
      name: string;
      /** Player Name */
      player_name?: string | null;
      /**
       * Race
       * @default humano
       */
      race: string;
      /** Alignment */
      alignment?: string | null;
      /** Size */
      size?: string | null;
      /** Speed Ft */
      speed_ft?: number | null;
      /** Notes */
      notes?: string | null;
      /** Portrait Url */
      portrait_url?: string | null;
      /** Class Levels */
      class_levels?: components["schemas"]["ClassLevelIn"][];
      /** Base Scores */
      base_scores?: {
        [key: string]: number;
      };
      /** Racial Bonus Choices */
      racial_bonus_choices?: {
        [key: string]: number;
      };
      /** Ability Damage */
      ability_damage?: {
        [key: string]: number;
      };
      /** Level Ability Increments */
      level_ability_increments?: {
        [key: string]: number;
      };
      /**
       * Max Hp
       * @default 0
       */
      max_hp: number;
      /**
       * Current Hp
       * @default 0
       */
      current_hp: number;
      /**
       * Temporary Hp
       * @default 0
       */
      temporary_hp: number;
      /**
       * Nonlethal Damage
       * @default 0
       */
      nonlethal_damage: number;
      /**
       * Hp Roll Mode
       * @default manual
       * @enum {string}
       */
      hp_roll_mode: "manual" | "average" | "max_first_then_average";
      /** Skill Ranks */
      skill_ranks?: {
        [key: string]: number;
      };
      /** Skill Misc Modifiers */
      skill_misc_modifiers?: {
        [key: string]: number;
      };
      /** Feats */
      feats?: string[];
      /** Feat Options */
      feat_options?: {
        [key: string]: string;
      };
      armor?: components["schemas"]["EquippedArmorIn"] | null;
      shield?: components["schemas"]["EquippedArmorIn"] | null;
      /** Weapons */
      weapons?: components["schemas"]["EquippedWeaponIn"][];
      /**
       * Natural Armor Bonus
       * @default 0
       */
      natural_armor_bonus: number;
      /**
       * Deflection Bonus
       * @default 0
       */
      deflection_bonus: number;
      /**
       * Other Ac Modifiers
       * @default 0
       */
      other_ac_modifiers: number;
      /** Load Carried Lb */
      load_carried_lb?: number | null;
      /** Active Conditions */
      active_conditions?: string[];
      /** Active Effects */
      active_effects?: components["schemas"]["ActiveEffectIn"][];
      /** Modifiers */
      modifiers?: components["schemas"]["ModifierIn"][];
      stances?: components["schemas"]["StancesIn"];
      /**
       * Initiative Misc
       * @default 0
       */
      initiative_misc: number;
      /**
       * Is Flat Footed
       * @default false
       */
      is_flat_footed: boolean;
      /**
       * Dexterity Denied
       * @default false
       */
      dexterity_denied: boolean;
      /** Id */
      id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * CharacterSummary
     * @description A dense row for the character list, with a few derived numbers.
     */
    CharacterSummary: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Player Name */
      player_name: string | null;
      /** Kind */
      kind: string;
      /** Classes */
      classes: string;
      /** Total Level */
      total_level: number;
      /** Max Hp */
      max_hp: number;
      /** Current Hp */
      current_hp: number;
      /** Armor Class */
      armor_class: number;
      /** Touch Ac */
      touch_ac: number;
      /** Flat Footed Ac */
      flat_footed_ac: number;
      /** Initiative */
      initiative: number;
      /** Fortitude */
      fortitude: number;
      /** Reflex */
      reflex: number;
      /** Will */
      will: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ClassLevelIn */
    ClassLevelIn: {
      /** Class Slug */
      class_slug: string;
      /** Level */
      level: number;
      /**
       * Is Prestige
       * @default false
       */
      is_prestige: boolean;
      /**
       * Is Favored
       * @default false
       */
      is_favored: boolean;
    };
    /** ClassProgressionRowDTO */
    ClassProgressionRowDTO: {
      /** Level */
      level: number;
      /** Bab */
      bab: string;
      /** Bab Iteratives */
      bab_iteratives: number[];
      /** Fort */
      fort: number;
      /** Ref */
      ref: number;
      /** Will */
      will: number;
      /** Special */
      special?: string | null;
      /** Spells Per Day */
      spells_per_day?: string[] | null;
    };
    /** ClassSummaryDTO */
    ClassSummaryDTO: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Hit Die */
      hit_die: string;
      /** Skill Ranks Per Level */
      skill_ranks_per_level: number;
      /** Bab Progression */
      bab_progression: string;
      /** Good Saves */
      good_saves: string[];
      /** Proficiencies */
      proficiencies?: string | null;
      /** Class Skills */
      class_skills: string[];
      /** Is Spellcaster */
      is_spellcaster: boolean;
      /** Is Prestige */
      is_prestige: boolean;
      /** Max Level */
      max_level: number;
    };
    /** CombatSheetResponse */
    CombatSheetResponse: {
      /** Abilities */
      abilities: {
        [key: string]: components["schemas"]["AbilityScoreDTO"];
      };
      ac: components["schemas"]["ACDTO"];
      /** Saves */
      saves: {
        [key: string]: components["schemas"]["ValueBreakdown"];
      };
      bab: components["schemas"]["BabDTO"];
      initiative: components["schemas"]["ValueBreakdown"];
      cmb: components["schemas"]["ValueBreakdown"];
      cmd: components["schemas"]["ValueBreakdown"];
      /** Attacks */
      attacks: components["schemas"]["AttackDTO"][];
      /** Skills */
      skills: components["schemas"]["SkillLineDTO"][];
      speed: components["schemas"]["SpeedDTO"];
      /** Armor Check Penalty */
      armor_check_penalty: number;
      /** Arcane Spell Failure */
      arcane_spell_failure: number;
      hp: components["schemas"]["HpDTO"];
      /** Carrying Capacity */
      carrying_capacity: {
        [key: string]: number;
      };
      /** Warnings */
      warnings: string[];
    };
    /** ConditionDTO */
    ConditionDTO: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Effect */
      effect: string;
    };
    /** CriticalDTO */
    CriticalDTO: {
      /** Threat Range */
      threat_range: number;
      /** Multiplier */
      multiplier: number;
    };
    /** EquippedArmorIn */
    EquippedArmorIn: {
      /** Catalog Name */
      catalog_name: string;
      /**
       * Enhancement Bonus
       * @default 0
       */
      enhancement_bonus: number;
      /**
       * Is Masterwork
       * @default false
       */
      is_masterwork: boolean;
      /** Material */
      material?: string | null;
      /** Custom Overrides */
      custom_overrides?: {
        [key: string]: unknown;
      } | null;
    };
    /** EquippedWeaponIn */
    EquippedWeaponIn: {
      /** Id */
      id?: string;
      /** Catalog Name */
      catalog_name: string;
      /**
       * Enhancement Bonus
       * @default 0
       */
      enhancement_bonus: number;
      /**
       * Is Masterwork
       * @default false
       */
      is_masterwork: boolean;
      /** Material */
      material?: string | null;
      /**
       * Wielding
       * @default one_handed
       * @enum {string}
       */
      wielding: "one_handed" | "two_handed" | "off_hand" | "natural";
      /** Size Category */
      size_category?: string | null;
      /** Ammo */
      ammo?: string | null;
      /** Notes */
      notes?: string | null;
      /** Custom Overrides */
      custom_overrides?: {
        [key: string]: unknown;
      } | null;
    };
    /** FeatDTO */
    FeatDTO: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Types */
      types: string[];
      /** Prerequisites */
      prerequisites?: string | null;
      /** Benefit */
      benefit?: string | null;
      /**
       * Is Eligible
       * @default true
       */
      is_eligible: boolean;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthResponse
     * @description Liveness payload.
     */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
      /** Version */
      version: string;
    };
    /** HpDTO */
    HpDTO: {
      /** Max */
      max: number;
      /** Current */
      current: number;
      /** Temporary */
      temporary: number;
      /** Nonlethal */
      nonlethal: number;
    };
    /** MetaDTO */
    MetaDTO: {
      bonus_types: components["schemas"]["BonusTypesDTO"];
      /** Abilities */
      abilities: components["schemas"]["AbilityDTO"][];
      /** Sizes */
      sizes: components["schemas"]["SizeDTO"][];
      /** Action Types */
      action_types: components["schemas"]["ActionTypeDTO"][];
      /** Units */
      units: {
        [key: string]: string;
      };
      /** Point Buy Costs */
      point_buy_costs: {
        [key: string]: number;
      };
    };
    /** ModifierIn */
    ModifierIn: {
      /** Id */
      id?: string;
      /** Target */
      target: string;
      /** Value */
      value: number;
      /** Bonus Type */
      bonus_type?: string | null;
      /** Source */
      source: string;
      /**
       * Source Kind
       * @default manual
       */
      source_kind: string;
      /** Condition */
      condition?: string | null;
      /**
       * Is Active
       * @default true
       */
      is_active: boolean;
      /** Expires In Rounds */
      expires_in_rounds?: number | null;
    };
    /** RaceDTO */
    RaceDTO: {
      /** Slug */
      slug: string;
      /** Key */
      key: string;
      /** Name */
      name: string;
      /** Size */
      size: string;
      /** Speed Ft */
      speed_ft: number;
      /** Ability Modifiers */
      ability_modifiers: {
        [key: string]: number;
      };
      /** Type */
      type: string;
      /** Vision */
      vision?: string | null;
      /** Traits */
      traits: string[];
      /** Languages */
      languages: {
        [key: string]: string[];
      };
    };
    /** SizeDTO */
    SizeDTO: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Ac Attack Mod */
      ac_attack_mod: number;
      /** Cmb Cmd Mod */
      cmb_cmd_mod: number;
      /** Stealth Mod */
      stealth_mod: number;
      /** Space */
      space: string;
      /** Reach */
      reach: string;
      /** Load Multiplier */
      load_multiplier: number;
    };
    /** SkillDTO */
    SkillDTO: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Ability */
      ability: string;
      /** Untrained */
      untrained: boolean;
      /** Armor Check Penalty */
      armor_check_penalty: boolean;
      /** Class For */
      class_for: string[];
    };
    /** SkillLineDTO */
    SkillLineDTO: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Ability */
      ability: string;
      /** Total */
      total: number;
      /** Is Class Skill */
      is_class_skill: boolean;
      /** Untrained Violation */
      untrained_violation: boolean;
      /** Breakdown */
      breakdown: components["schemas"]["BreakdownEntry"][];
      /** Suppressed */
      suppressed: components["schemas"]["SuppressedEntry"][];
    };
    /** SpeedDTO */
    SpeedDTO: {
      /** Base Ft */
      base_ft: number;
      /** Final Ft */
      final_ft: number;
      /** Reductions */
      reductions: string[];
    };
    /** SpellDTO */
    SpellDTO: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** School */
      school?: string | null;
      /** Levels */
      levels: {
        [key: string]: number;
      };
      /** Descriptors */
      descriptors: string[];
      /** Casting Time */
      casting_time?: string | null;
      /** Components */
      components?: string | null;
      /** Range */
      range?: string | null;
      /** Duration */
      duration?: string | null;
      /** Saving Throw */
      saving_throw?: string | null;
      /** Spell Resistance */
      spell_resistance?: string | null;
    };
    /** StancesIn */
    StancesIn: {
      /**
       * Charge
       * @default false
       */
      charge: boolean;
      /**
       * Fighting Defensively
       * @default false
       */
      fighting_defensively: boolean;
      /**
       * Total Defense
       * @default false
       */
      total_defense: boolean;
      /**
       * Power Attack
       * @default false
       */
      power_attack: boolean;
      /**
       * Combat Expertise
       * @default false
       */
      combat_expertise: boolean;
      /**
       * Flanking
       * @default false
       */
      flanking: boolean;
      /**
       * Higher Ground
       * @default false
       */
      higher_ground: boolean;
    };
    /** SuppressedEntry */
    SuppressedEntry: {
      /** Label */
      label: string;
      /** Value */
      value: number;
      /** Type */
      type: string | null;
      /** Reason */
      reason: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** ValueBreakdown */
    ValueBreakdown: {
      /** Total */
      total: number;
      /** Breakdown */
      breakdown: components["schemas"]["BreakdownEntry"][];
      /** Suppressed */
      suppressed: components["schemas"]["SuppressedEntry"][];
    };
    /** WeaponDTO */
    WeaponDTO: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Proficiency */
      proficiency: string;
      /** Category */
      category: string;
      /** Cost */
      cost?: string | null;
      /** Damage Small */
      damage_small?: string | null;
      /** Damage Medium */
      damage_medium?: string | null;
      /** Critical */
      critical: components["schemas"]["CriticalDTO"][];
      /** Range Increment */
      range_increment?: string | null;
      /** Weight */
      weight?: string | null;
      /** Damage Type */
      damage_type?: string | null;
      /** Special */
      special?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  get_meta_api_v1_rules_meta_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetaDTO"];
        };
      };
    };
  };
  get_races_api_v1_rules_races_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RaceDTO"][];
        };
      };
    };
  };
  get_classes_api_v1_rules_classes_get: {
    parameters: {
      query?: {
        include_prestige?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClassSummaryDTO"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_class_progression_api_v1_rules_classes__slug__progression__level__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        level: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClassProgressionRowDTO"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_skills_api_v1_rules_skills_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SkillDTO"][];
        };
      };
    };
  };
  get_feats_api_v1_rules_feats_get: {
    parameters: {
      query?: {
        bab?: number;
        abilities?: string[];
        owned?: string[];
        type?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeatDTO"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_weapons_api_v1_rules_weapons_get: {
    parameters: {
      query?: {
        category?: string | null;
        proficiency?: string | null;
        search?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WeaponDTO"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_armor_api_v1_rules_armor_get: {
    parameters: {
      query?: {
        category?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArmorDTO"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_conditions_api_v1_rules_conditions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConditionDTO"][];
        };
      };
    };
  };
  get_spells_api_v1_rules_spells_get: {
    parameters: {
      query?: {
        class?: string | null;
        level?: number | null;
        search?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SpellDTO"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_characters_api_v1_characters_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        search?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CharacterListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_character_api_v1_characters_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CharacterCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CharacterRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  import_character_api_v1_characters_import_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CharacterImport"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CharacterRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_character_api_v1_characters__character_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        character_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CharacterRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  replace_character_api_v1_characters__character_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        character_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CharacterCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CharacterRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_character_api_v1_characters__character_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        character_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_character_api_v1_characters__character_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        character_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CharacterPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CharacterRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  export_character_api_v1_characters__character_id__export_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        character_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CharacterRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  duplicate_character_api_v1_characters__character_id__duplicate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        character_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CharacterRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  combat_sheet_api_v1_characters__character_id__combat_sheet_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        character_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CombatSheetResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  derive_api_v1_derive_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CharacterCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CombatSheetResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
