/**
 * Typed rules-catalog fixtures for the editor tests. Typed against the generated
 * OpenAPI models so a mock that drifts from the contract fails to compile.
 */
import type {
  AlignmentDTO,
  ArmorDTO,
  ClassSummaryDTO,
  ConditionDTO,
  FeatDTO,
  MetaDTO,
  RaceDTO,
  SkillDTO,
  WeaponDTO,
} from "@/api/types";

export const meta: MetaDTO = {
  bonus_types: {
    always_stack: ["esquiva"],
    do_not_stack: ["armadura"],
    penalties: "…",
    note: null,
  },
  abilities: [],
  sizes: [],
  action_types: [],
  units: {},
  point_buy_costs: {
    "7": -4,
    "8": -2,
    "9": -1,
    "10": 0,
    "11": 1,
    "12": 2,
    "13": 3,
    "14": 5,
    "15": 7,
    "16": 10,
    "17": 13,
    "18": 17,
  },
  feat_levels: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19],
  ability_increment_levels: [4, 8, 12, 16, 20],
  favored_class_note: "+1 pg o +1 rango de habilidad por nivel tomado en la clase favorita",
  item_slots: [
    { name: "anillo (×2)", slug: "anillo", capacity: 2 },
    { name: "cuello", slug: "cuello", capacity: 1 },
    { name: "manos", slug: "manos", capacity: 1 },
  ],
  item_categories: ["anillos", "objetos maravillosos", "bastones", "varitas"],
  item_activations: ["uso continuo", "palabra de mando"],
  max_item_enhancement: 5,
  feat_types: ["General", "Combate", "Metamágica"],
};

export const alignments: AlignmentDTO[] = [
  { code: "LB", name: "Legal bueno" },
  { code: "LN", name: "Legal neutral" },
  { code: "CM", name: "Caótico maligno" },
];

export const races: RaceDTO[] = [
  {
    slug: "humano",
    key: "humano",
    name: "Humano",
    size: "Mediano",
    speed_ft: 30,
    ability_modifiers: { cualquiera: 2 },
    type: "humanoide",
    vision: null,
    traits: [],
    languages: { inicio: ["común"], adicionales: [] },
    bonus_feats: [{ level: 1, choice: "libre", types: [] }],
    weapon_proficiencies: [],
    weapon_words: [],
  },
  {
    slug: "mediano",
    key: "mediano",
    name: "Mediano",
    size: "Pequeño",
    speed_ft: 20,
    ability_modifiers: { Des: 2, Car: 2, Fue: -2 },
    type: "humanoide",
    vision: null,
    traits: [],
    languages: { inicio: ["común"], adicionales: [] },
    bonus_feats: [],
    weapon_proficiencies: ["Honda"],
    weapon_words: ["mediano", "mediana"],
  },
];

export const classes: ClassSummaryDTO[] = [
  {
    slug: "guerrero",
    name: "Guerrero",
    hit_die: "d10",
    hit_die_faces: 10,
    hit_points_floor: 6,
    skill_ranks_per_level: 2,
    bab_progression: "completo",
    good_saves: ["Fortaleza"],
    proficiencies: "todas las armas sencillas y marciales",
    class_skills: ["Intimidar", "Trepar"],
    is_spellcaster: false,
    is_prestige: false,
    max_level: 20,
    bonus_feats: [],
  },
  {
    slug: "mago",
    name: "Mago",
    hit_die: "d6",
    hit_die_faces: 6,
    hit_points_floor: 4,
    skill_ranks_per_level: 2,
    bab_progression: "1/2",
    good_saves: ["Voluntad"],
    proficiencies: "bastón, daga",
    class_skills: ["Saber (arcano)"],
    is_spellcaster: true,
    is_prestige: false,
    max_level: 20,
    bonus_feats: [],
  },
];

export const skills: SkillDTO[] = [
  {
    slug: "intimidar",
    name: "Intimidar",
    ability: "Car",
    untrained: true,
    armor_check_penalty: false,
    class_for: ["guerrero"],
  },
  {
    slug: "trepar",
    name: "Trepar",
    ability: "Fue",
    untrained: true,
    armor_check_penalty: true,
    class_for: ["guerrero"],
  },
  {
    slug: "acrobacias",
    name: "Acrobacias",
    ability: "Des",
    untrained: true,
    armor_check_penalty: true,
    class_for: ["picaro"],
  },
];

/** A feat the backend classifies as a round-long choice, not a way of attacking. */
export const stanceFeat: FeatDTO = {
  slug: "hendedura",
  name: "Hendedura",
  types: ["Combate"],
  prerequisites: "Fue 13, Ataque poderoso, ataque base +1",
  benefit: "Atacas a un segundo enemigo adyacente a costa de -2 a la CA.",
  is_eligible: true,
  activation: "estandar",
  is_stance: true,
  effects: [
    {
      condition: null,
      when: {},
      modifiers: [{ target: "ca", bonus_type: "penalizador", value: -2 }],
      substitutions: [],
      rules: [],
    },
  ],
};

export const feats: FeatDTO[] = [
  stanceFeat,
  {
    slug: "esquiva",
    name: "Esquiva",
    types: ["Combate"],
    prerequisites: null,
    benefit: "+1 CA",
    is_eligible: true,
    activation: "pasiva",
    is_stance: false,
    effects: [
      {
        condition: null,
        when: {},
        modifiers: [{ target: "ca", bonus_type: "esquiva", value: 1 }],
        substitutions: [],
        rules: ["Pierdes este bonificador cuando pierdes tu bonificador por Destreza a la CA."],
      },
    ],
  },
  {
    slug: "acometer",
    name: "Acometer",
    types: ["Combate"],
    prerequisites: "ataque base +6",
    benefit: "Atacas con un arma de alcance a enemigos fuera de tu alcance.",
    is_eligible: false,
    activation: "pasiva",
    is_stance: false,
    effects: [],
  },
  {
    slug: "soltura-con-un-arma",
    name: "Soltura con un arma",
    types: ["Combate"],
    prerequisites: null,
    benefit: "+1 a las tiradas de ataque con el arma elegida.",
    is_eligible: true,
    activation: "pasiva",
    is_stance: false,
    choice_kind: "weapon",
    effects: [
      {
        condition: null,
        when: {},
        modifiers: [{ target: "ataque_arma_seleccionada", bonus_type: "sin_tipo", value: 1 }],
        substitutions: [],
        rules: [],
      },
    ],
  },
  {
    slug: "abstencion-de-materiales",
    name: "Abstención de materiales",
    types: ["General"],
    prerequisites: null,
    benefit: "Lanzas conjuros con componente material barato sin gastarlo.",
    is_eligible: true,
    activation: "pasiva",
    is_stance: false,
    effects: [],
  },
];

export const weapons: WeaponDTO[] = [
  {
    slug: "espada-larga",
    name: "Espada larga",
    proficiency: "marcial",
    category: "Armas cuerpo a cuerpo a una mano",
    cost: "15 po",
    damage_small: "1d6",
    damage_medium: "1d8",
    critical: [{ threat_range: 19, multiplier: 2 }],
    range_increment: null,
    weight: "4 libras",
    damage_type: "Cor",
    special: null,
  },
  {
    slug: "daga",
    name: "Daga",
    proficiency: "sencilla",
    category: "Armas cuerpo a cuerpo ligeras",
    cost: "2 po",
    damage_small: "1d3",
    damage_medium: "1d4",
    critical: [{ threat_range: 19, multiplier: 2 }],
    range_increment: "10 pies (3 m)",
    weight: "1 libra",
    damage_type: "Per o Cor",
    special: null,
  },
  {
    slug: "arco-largo",
    name: "Arco largo",
    proficiency: "marcial",
    category: "Armas a distancia",
    cost: "75 po",
    damage_small: "1d6",
    damage_medium: "1d8",
    critical: [{ threat_range: 20, multiplier: 3 }],
    range_increment: "100 pies (30 m)",
    weight: "3 libras",
    damage_type: "Per",
    special: null,
  },
  {
    slug: "lanza-larga",
    name: "Lanza larga",
    proficiency: "sencilla",
    category: "Armas cuerpo a cuerpo a dos manos",
    cost: "5 po",
    damage_small: "1d6",
    damage_medium: "1d8",
    critical: [{ threat_range: 20, multiplier: 3 }],
    range_increment: null,
    weight: "9 libras",
    damage_type: "Per",
    special: "apuntalar, alcance",
  },
];

export const armor: ArmorDTO[] = [
  {
    slug: "cota-de-escamas",
    name: "Cota de escamas",
    category: "intermedia",
    price_gp: 50,
    armor_bonus: 5,
    max_dex: 3,
    armor_check_penalty: -4,
    arcane_spell_failure_pct: 25,
    speed_30: null,
    speed_20: null,
    weight: "30 libras",
  },
  {
    slug: "escudo-pesado-de-acero",
    name: "Escudo pesado de acero",
    category: "escudo",
    price_gp: 20,
    armor_bonus: 2,
    max_dex: null,
    armor_check_penalty: -2,
    arcane_spell_failure_pct: 15,
    speed_30: null,
    speed_20: null,
    weight: "15 libras",
  },
];

export const conditions: ConditionDTO[] = [
  { slug: "fatigado", name: "Fatigado", effect: "-2 a Fue y Des." },
  { slug: "cegado", name: "Cegado", effect: "-2 a la CA, pierde Des." },
  { slug: "sacudido", name: "Sacudido", effect: "-2 a ataques, salvaciones y pruebas." },
];
